spring:
  application:
    name: cqtt
  docker:
    compose:
      file: docker-compose.yaml
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://localhost:35432/employees
    username: postgres
    password: 123456
server:
  port: 8080
